Rules = {
  "PROGRAMbegin": "PROGRAM=begin STATEMENT_LIST end",
  "STATEMENT_LISTread": "STATEMENT_LIST=STATEMENT STATEMENTS",
  "STATEMENT_LISTwrite": "STATEMENT_LIST=STATEMENT STATEMENTS",
  "STATEMENT_LISTif": "STATEMENT_LIST=STATEMENT STATEMENTS",
  "STATEMENT_LISTident": "STATEMENT_LIST=STATEMENT STATEMENTS",
  "STATEMENTSend": "STATEMENT=e",
  "STATEMENTSwrite": "STATEMENTS=STATEMENT STATEMENTS",
  "STATEMENTSwrite": "STATEMENTS=STATEMENT STATEMENTS",
  "STATEMENTSTif": "STATEMENTS=STATEMENT STATEMENTS",
  "STATEMENTSident": "STATEMENTS=STATEMENT STATEMENTS",
  "STATEMENTread": "STATEMENT=read openparen ID_LIST closeparen semicolon",
}


